Vignoble: lib/cultivationtask.lib.php File Reference
cultivationtask.lib.php File Reference
Cultivation management
Contains common functions for cultivation task management.
Functions
setIsCultivationProject ()
Initialize project Id with default cultivation project.
displayProjectHeaderCard ($object, $form)
Display a project card summary.
displayTaskHeader ($object, $projectstatic, $form)
print the task ref and label with navigation links in task list.
showtasks (&$inc, $parent, &$lines, &$level, $var, $showproject, &$taskrole, $projectsListId= '', $addordertick=0, $projectidfortotallink=0)
Show task lines with a particular parent.
getTaskUrl ($task, $withpicto=0, $option= '', $mode= 'cultivationtask', $addlabel=0, $sep= '- ', $notooltip=0)
Return cultivation task clicable name (with picto eventually)
createNewTask ()
Create a new task for the project in database Use the getpost variable from the new task form.
get_dolusers ($force_entity=0, $morefilter= '', $noactive=0)
Return array list of users.
getProjectContributors ($task, $projectstatic)
Get list of users who could be allocated to project task.
Detailed Description
Contains common functions for cultivation task management.
Definition in file cultivationtask.lib.php.
Function Documentation
createNewTask ()
Create a new task for the project in database Use the getpost variable from the new task form.
Definition at line 506 of file cultivationtask.lib.php.
References $conf, $db, $langs, and $user.
displayProjectHeaderCard ($object, $form)
Display a project card summary.
Shows header (ref and title) with key fields : visibility, begin and end date, description, categories
Parameters
object the project to display
form the form object
Definition at line 64 of file cultivationtask.lib.php.
References $conf, $db, $form, $langs, $object, $user, and print.
displayTaskHeader ($object, $projectstatic, $form)
print the task ref and label with navigation links in task list.
Parameters
object the task to display
projectstatic the project linked to the task
form the form object to display
Definition at line 150 of file cultivationtask.lib.php.
References $conf, $db, $form, $langs, $object, $user, and print.
get_dolusers ($force_entity = 0, $morefilter = '', $noactive = 0)
Return array list of users.
Parameters
int $force_entity 0 or Id of environment to force
string $morefilter Add more filters into sql request
int $noactive Show only active users (this will also happened whatever is this option if USER_HIDE_INACTIVE_IN_COMBOBOX is on).
Returns
array list of users
Definition at line 523 of file cultivationtask.lib.php.
References $conf, $db, $langs, $resql, $sql, and $user.
Referenced by addTaskUser(), addTimeSpent(), and getProjectContributors().
getProjectContributors ($task, $projectstatic)
Get list of users who could be allocated to project task.
Parameters
Task $task the current task
Project $projectstatic the cultivation project
Returns
array[] list of contributors for project
Definition at line 581 of file cultivationtask.lib.php.
References $conf, $db, $langs, $projectstatic, $user, $value, and get_dolusers().
Referenced by displayAddTimeSpentForm(), and displayAddUserForm().
getTaskUrl ($task, $withpicto = 0, $option = '', $mode = 'cultivationtask', $addlabel = 0, $sep = ' - ', $notooltip = 0)
Return cultivation task clicable name (with picto eventually)
Parameters
object $task the task to process
int $withpicto 0=No picto, 1=Include picto into link, 2=Only picto
string $option 'withproject' or ''
string $mode Mode 'task', 'time', 'contact', 'note', document' define page to link to.
int $addlabel 0=Default, 1=Add label into string, >1=Add first chars into string
string $sep Separator between ref and label if option addlabel is set
int $notooltip 1=Disable tooltip
Returns
string Chaine avec URL
Definition at line 458 of file cultivationtask.lib.php.
References $conf, $label, $langs, $mode, $result, and $user.
Referenced by showtasks().
setIsCultivationProject ()
Initialize project Id with default cultivation project.
Also setup global key VIGNOBLE_ISCULTIVATIONPROJECT to true for tabs management
Returns
$id Default cultivation project id, 0 if not found
Definition at line 36 of file cultivationtask.lib.php.
References $conf, $db, $id, $langs, and $user.
showtasks (& $inc, $parent, & $lines, & $level, $var, $showproject, & $taskrole, $projectsListId = '', $addordertick = 0, $projectidfortotallink = 0)
Show task lines with a particular parent.
Parameters
string $inc Line number (start to 0, then increased by recursive call)
string $parent Id of parent project to show (0 to show all)
Task[] $lines Array of lines
int $level Level (start to 0, then increased/decrease by recursive call), or -1 to show all level in order of $lines without the recursive groupment feature.
string $var Color
int $showproject Show project columns
int $taskrole Array of roles of user for each tasks
int $projectsListId List of id of project allowed to user (string separated with comma)
int $addordertick Add a tick to move task
int $projectidfortotallink 0 or Id of project to use on total line (link to see all time consumed for project)
Returns
void
Definition at line 195 of file cultivationtask.lib.php.
References $conf, $langs, $projectstatic, $taskstatic, $user, getTaskUrl(), if, and print.