Vignoble: admin/module_about.php File Reference
module_about.php File Reference
Module administration
Displays module information in a Setup Tab Tab content :
Variables
if(!$user->admin) $action = GETPOST('action', 'alpha')
$page_name = "vignobleSetup"
$linkback = '<a href="' . DOL_URL_ROOT . '/admin/modules.php">' . $langs->trans("BackToModuleList") . '</a>'
$head = vignobleAdminPrepareHead()
switch ($langs->getDefaultLang())
dol_buildpath('/vignoble/COPYING', 1). '">' dol_buildpath ('/vignoble/img/gplv3.png', 1). '"/>'
Detailed Description
Displays module information in a Setup Tab Tab content :
README.md file for the module
COPYING file for the module
GPLV3 licence link
Definition in file module_about.php.
Variable Documentation
if (!$user->admin) $action = GETPOST('action', 'alpha')
Definition at line 50 of file module_about.php.
$head = vignobleAdminPrepareHead()
Definition at line 68 of file module_about.php.
$linkback = '<a href="' . DOL_URL_ROOT . '/admin/modules.php">' . $langs->trans("BackToModuleList") . '</a>'
Definition at line 64 of file module_about.php.
Referenced by FormVignoble\printObjectRef(), and printView().
$page_name = "vignobleSetup"
Definition at line 60 of file module_about.php.
Referenced by printView().
dol_buildpath ('/vignoble/COPYING', 1). '">' dol_buildpath('/vignoble/img/gplv3.png', 1). '"/>'
Definition at line 83 of file module_about.php.
Referenced by ActionsVignoble\addSearchEntry(), plot\getNomUrl(), FormVignoble\printObjectRef(), printView(), and vignobleAdminPrepareHead().
switch($langs->getDefaultLang())
Definition at line 74 of file module_about.php.