Vignoble: cultivationtask.php File Reference
cultivationtask.php File Reference
Cultivation management
Card page of a cultivation project task.
Functions
displayTaskCard ($object, $extrafields)
Display task fields & extrafields on one column.
displayTaskEditForm ($withproject, $object, $projectstatic, $form, $formother, $extrafields)
Variables
$cultivationprojectid = setIsCultivationProject()
$id = GETPOST('id', 'int')
$ref = GETPOST("ref", 'alpha', 1)
$taskref = GETPOST("taskref", 'alpha')
$action = GETPOST('action', 'alpha')
$confirm = GETPOST('confirm', 'alpha')
$withproject = GETPOST('withproject', 'int')
$project_ref = GETPOST('project_ref', 'alpha')
$planned_workload = ((GETPOST('planned_workloadhour') != '' && GETPOST('planned_workloadmin') != '') ? GETPOST('planned_workloadhour') * 3600 + GETPOST('planned_workloadmin') * 60 : '')
$socid = 0
$object = new Task($db)
$extrafields = new ExtraFields($db)
$projectstatic = new Project($db)
$extralabels = $extrafields->fetch_name_optionals_label($object->table_element)
$form = new Form($db)
$formother = new FormOther($db)
Detailed Description
Card page of a cultivation project task.
Definition in file cultivationtask.php.
Function Documentation
displayTaskCard ($object, $extrafields)
Display task fields & extrafields on one column.
Parameters
object the task to display
extrafields the task extra fields
Definition at line 218 of file cultivationtask.php.
References $conf, $db, $extrafields, $langs, $object, $user, and print.
displayTaskEditForm ($withproject, $object, $projectstatic, $form, $formother, $extrafields)
Parameters
withproject
object
projectstatic
form
formother
head
Definition at line 285 of file cultivationtask.php.
References $_SERVER, $_SESSION, $conf, $db, $extrafields, $form, $formother, $langs, $object, $user, $withproject, and print.
Variable Documentation
$action = GETPOST('action', 'alpha')
Definition at line 36 of file cultivationtask.php.
Referenced by ActionsVignoble\doActions(), and pdf_plotabc\write_file().
$confirm = GETPOST('confirm', 'alpha')
Definition at line 37 of file cultivationtask.php.
$cultivationprojectid = setIsCultivationProject()
Definition at line 31 of file cultivationtask.php.
$extrafields = new ExtraFields($db)
Definition at line 56 of file cultivationtask.php.
Referenced by displayTaskCard(), displayTaskEditForm(), plot\fetch(), modVignoble\getExports(), modVignoble\getImports(), and plot\loadObject().
$extralabels = $extrafields->fetch_name_optionals_label($object->table_element)
Definition at line 60 of file cultivationtask.php.
Referenced by plot\fetch(), and plot\loadObject().
$form = new Form($db)
Definition at line 149 of file cultivationtask.php.
Referenced by displayProjectHeaderCard(), displaySearchForm(), displayTaskEditForm(), displayTaskHeader(), and FormVignoble\printObjectRef().
$formother = new FormOther($db)
Definition at line 150 of file cultivationtask.php.
Referenced by displayTaskEditForm().
$id = GETPOST('id', 'int')
Definition at line 33 of file cultivationtask.php.
Referenced by Plotcultivationtask\create(), plot\create(), Plotcultivationtask\delete(), plot\delete(), Plotcultivationtask\fetch(), plot\fetch(), Plotcultivationtask\info(), plot\info(), Plotcultivationtask\loadObject(), plot\loadObject(), setIsCultivationProject(), Plotcultivationtask\update(), and plot\update().
$object = new Task($db)
Definition at line 55 of file cultivationtask.php.
Referenced by pdf_plotabc\_pagefoot(), pdf_plotabc\_pagehead(), pdf_plotabc\_tableau_info(), pdf_plotabc\_tableau_tot(), Plotcultivationtask\createFromClone(), plot\createFromClone(), displayProjectHeaderCard(), displayTaskCard(), displayTaskEditForm(), displayTaskHeader(), ActionsVignoble\doActions(), FormVignoble\getTabsHeader(), FormVignoble\printObjectRef(), and pdf_plotabc\write_file().
$planned_workload = ((GETPOST('planned_workloadhour') != '' && GETPOST('planned_workloadmin') != '') ? GETPOST('planned_workloadhour') * 3600 + GETPOST('planned_workloadmin') * 60 : '')
Definition at line 40 of file cultivationtask.php.
$project_ref = GETPOST('project_ref', 'alpha')
Definition at line 39 of file cultivationtask.php.
$projectstatic = new Project($db)
Definition at line 57 of file cultivationtask.php.
Referenced by showtasks().
$ref = GETPOST("ref", 'alpha', 1)
Definition at line 34 of file cultivationtask.php.
Referenced by Plotcultivationtask\getNomUrl().
$socid = 0
Definition at line 43 of file cultivationtask.php.
$taskref = GETPOST("taskref", 'alpha')
Definition at line 35 of file cultivationtask.php.
$withproject = GETPOST('withproject', 'int')
Definition at line 38 of file cultivationtask.php.
Referenced by displayTaskEditForm().