Vignoble: admin/admin_vignoble.php File Reference
admin_vignoble.php File Reference
Functions
printView ($langs, $user)
generate and print the view
Variables
if(false===(@include '../../main.inc.php')) global $langs
if(false===(@include '../../main.inc.php')) global $user
if(!$user->admin) $action = GETPOST('action','alpha')
$value = GETPOST('value','alpha')
$label = GETPOST('label','alpha')
$scandir = GETPOST('scandir','alpha')
$type ='plot'
if($action== 'specimen') else if($action== 'set') else if($action== 'del') else if($action== 'setdoc') $dirmodels =array_merge(array('/'),(array) $conf->modules_parts['models'])
Function Documentation
printView ($langs, $user)
generate and print the view
Definition at line 155 of file admin_vignoble.php.
References $dirmodels, $form, $head, $linkback, $page_name, $resql, $sql, $type, dol_buildpath, print, and vignobleAdminPrepareHead().
Variable Documentation
if (!$user->admin) $action = GETPOST('action','alpha')
Definition at line 51 of file admin_vignoble.php.
if ($action== 'specimen') else if ($action== 'set') else if ($action== 'del') else if ($action== 'setdoc') $dirmodels =array_merge(array('/'),(array) $conf->modules_parts['models'])
Definition at line 147 of file admin_vignoble.php.
Referenced by printView().
$label = GETPOST('label','alpha')
Definition at line 53 of file admin_vignoble.php.
if (false===(@include '../../main.inc.php')) global $langs
Definition at line 28 of file admin_vignoble.php.
$scandir = GETPOST('scandir','alpha')
Definition at line 54 of file admin_vignoble.php.
$type ='plot'
Definition at line 55 of file admin_vignoble.php.
Referenced by ModelePDFPlot\liste_modeles(), ModeleVignoble\liste_modeles(), and printView().
if (false===(@include '../../main.inc.php')) global $user
Definition at line 28 of file admin_vignoble.php.
$value = GETPOST('value','alpha')
Definition at line 52 of file admin_vignoble.php.
Referenced by plot\fetchAll().