Vignoble: cultivationtasks.php File Reference
cultivationtasks.php File Reference
Cultivation management
List all tasks of the default cultivation project.
Variables
$id = setIsCultivationProject()
$action = GETPOST('action', 'alpha')
Get page variables.
$ref = GETPOST('ref', 'alpha')
$taskref = GETPOST('taskref', 'alpha')
$backtopage = GETPOST('backtopage', 'alpha')
$cancel = GETPOST('cancel')
$mode = GETPOST('mode', 'alpha')
$mine = ($mode == 'mine' ? 1 : 0)
$object = new Project($db)
Instanciate.
$taskstatic = new Task($db)
$extrafields_task = new ExtraFields($db)
if ($cancel) = $db->plimit($conf->liste_limit + 1, $offset)
Fetch $object using $id or $ref $action should not be create or createtask $cancel should be empty.
$extralabels_task = $extrafields_task->fetch_name_optionals_label($taskstatic->table_element)
Get extrafields.
$socid = 0
$result = restrictedArea($user, 'projet', $id, 'projet&project')
$progress = GETPOST('progress', 'int')
$label = GETPOST('label', 'alpha')
$description = GETPOST('description')
$planned_workload = GETPOST('planned_workloadhour') * 3600 + GETPOST('planned_workloadmin') * 60
if($action== 'createtask'&&$user->rights->projet->creer) $form = new Form($db)
Process actions : createtask else do nothing.
$formother = new FormOther($db)
$title = $langs->trans("Cultivation") . ' - ' . $langs->trans("Tasks") . ' - ' . $object->ref . ' ' . $object->title
$help_url = "EN:Module_Projects|FR:Module_Projets|ES:M&oacute;dulo_Proyectos"
if($id > 0||!empty($ref)) print
if($action== 'create'&&$user->rights->projet->creer &&(empty($object->thirdparty->id)||$userWrite > 0)) else if($id > 0||!empty($ref)) else
Detailed Description
List all tasks of the default cultivation project.
Called by the cultivation option in the module menu. Also allow to create a new task using the menu link.
Definition in file cultivationtasks.php.
Variable Documentation
$action = GETPOST('action', 'alpha')
Get page variables.
Definition at line 40 of file cultivationtasks.php.
$backtopage = GETPOST('backtopage', 'alpha')
Definition at line 43 of file cultivationtasks.php.
$cancel = GETPOST('cancel')
Definition at line 44 of file cultivationtasks.php.
$description = GETPOST('description')
Definition at line 89 of file cultivationtasks.php.
$extrafields_task = new ExtraFields($db)
Definition at line 58 of file cultivationtasks.php.
$extralabels_task = $extrafields_task->fetch_name_optionals_label($taskstatic->table_element)
Get extrafields.
Definition at line 73 of file cultivationtasks.php.
if ($action== 'createtask'&&$user->rights->projet->creer) $form = new Form($db)
Process actions : createtask else do nothing.
Display View
Definition at line 186 of file cultivationtasks.php.
$formother = new FormOther($db)
Definition at line 187 of file cultivationtasks.php.
$help_url = "EN:Module_Projects|FR:Module_Projets|ES:M&oacute;dulo_Proyectos"
Definition at line 193 of file cultivationtasks.php.
$id = setIsCultivationProject()
Definition at line 35 of file cultivationtasks.php.
$label = GETPOST('label', 'alpha')
Definition at line 88 of file cultivationtasks.php.
Referenced by getTaskUrl().
$mine = ($mode == 'mine' ? 1 : 0)
Definition at line 47 of file cultivationtasks.php.
$mode = GETPOST('mode', 'alpha')
Definition at line 45 of file cultivationtasks.php.
Referenced by displayProjectCard(), Plotcultivationtask\getLibStatut(), plot\getLibStatut(), getTaskUrl(), Plotcultivationtask\LibStatut(), and plot\LibStatut().
$object = new Project($db)
Instanciate.
object as project class
taskstatic as task class
add extrafields for both.
Definition at line 56 of file cultivationtasks.php.
$planned_workload = GETPOST('planned_workloadhour') * 3600 + GETPOST('planned_workloadmin') * 60
Definition at line 90 of file cultivationtasks.php.
$progress = GETPOST('progress', 'int')
Definition at line 87 of file cultivationtasks.php.
$ref = GETPOST('ref', 'alpha')
Definition at line 41 of file cultivationtasks.php.
$result = restrictedArea($user, 'projet', $id, 'projet&project')
Definition at line 79 of file cultivationtasks.php.
Referenced by plot\create(), createDefaultFields(), Plotcultivationtask\createFromClone(), plot\createFromClone(), plot\delete(), Plotcultivationtask\getNomUrl(), plot\getNomUrl(), getTaskUrl(), Plotcultivationtask\info(), plot\info(), modVignoble\init(), and plot\update().
$socid = 0
Definition at line 76 of file cultivationtasks.php.
$taskref = GETPOST('taskref', 'alpha')
Definition at line 42 of file cultivationtasks.php.
$taskstatic = new Task($db)
Definition at line 57 of file cultivationtasks.php.
Referenced by showtasks().
$title = $langs->trans("Cultivation") . ' - ' . $langs->trans("Tasks") . ' - ' . $object->ref . ' ' . $object->title
Definition at line 190 of file cultivationtasks.php.
Referenced by pdf_plotabc\_pagehead().
if ($action== 'create'&&$user->rights->projet->creer &&(empty($object->thirdparty->id)||$userWrite > 0)) else if ($id > 0||!empty($ref)) else
Initial value:
{
        print '<a href="' . DOL_URL_ROOT . '/custom/vignoble/admin/module_settings.php">' . $langs->trans("VignobleSetup") . '</a>'
Definition at line 392 of file cultivationtasks.php.
* if = $db->plimit($conf->liste_limit + 1, $offset)
Fetch $object using $id or $ref $action should not be create or createtask $cancel should be empty.
Definition at line 64 of file cultivationtasks.php.
Referenced by showtasks().
print
Definition at line 196 of file cultivationtasks.php.