Vignoble: plot_card.php File Reference
plot_card.php File Reference
Plot management
The plot card displays the main attributes of the plot.
Functions
addPlot (plot $object, ExtraFields $extrafields)
Add plot entered in Add Plot Form to the database.
displayAddPlotForm (plot $object, ExtraFields $extrafields)
Display the form to enter a new plot.
updatePlot (plot $object, ExtraFields $extrafields)
Update Plot information in database using the Plot Edit Form data.
deletePlot (plot $object)
Delete selected plot from database.
buildPlotDocument (plot $object)
Build plot document.
removePlotFile (plot $object)
Remove file associated to current object.
displayPlotEditForm (plot $object, ExtraFields $extrafields)
Display the Plot Edit Form.
displayPlotTab ($action, plot $object, ExtraFields $extrafields)
Display the proper Plot Tab based on the tab parameter usin GETPOST.
displayPlotCard ($action, plot $object, ExtraFields $extrafields, Form $form)
Display the plot card in read mode.
displayPlotTasks (plot $plot, Form $form)
Display the tasks table for the plot.
getTasksort ()
Get fields and order used for the plot task table sort.
getTaskfilter ($id)
Get all data needed to filter the SQL requests on plot task and produce the results.
buildTaskSearchParameters ($filter)
Build the parameters string to be added to URL to keep the filter conditions.
displayPlotTaskLines ($plottask)
Display the plot task lines in a table in read only mode.
getTabsHeader ($langs, $object)
Set up the 4 Tabs : Card, Tasks, Notes, Info.
Variables
$id = GETPOST('id', 'int')
$ref = GETPOST('ref', 'alpha')
$action = GETPOST('action', 'alpha')
$confirm = GETPOST('confirm', 'alpha')
$cancel = GETPOST('cancel', 'alpha')
$tab = GETPOST('tab', 'alpha')
$object = new plot($db)
$extrafields = new ExtraFields($db)
if(($id > 0||!empty($ref))) else
Detailed Description
The plot card displays the main attributes of the plot.
Attributes are in view mode first. The user could use the form to update, create or delete an object. Top of the form is standardised to display the object identity and navigate the object list.
Definition in file plot_card.php.
Function Documentation
addPlot (plot $object, ExtraFields $extrafields)
Add plot entered in Add Plot Form to the database.
Parameters
plot $object
ExtraFields $extrafields
Returns
string
Definition at line 116 of file plot_card.php.
References $action, $conf, $db, $error, $id, $langs, $user, and plot\create().
buildPlotDocument (plot $object)
Build plot document.
Not in use yet - see comments end of page.
Parameters
plot $object
Definition at line 272 of file plot_card.php.
References $action, $conf, $db, $langs, $result, $user, and plot\generateDocument().
buildTaskSearchParameters ($filter)
Build the parameters string to be added to URL to keep the filter conditions.
(used for list sort)
Parameters
Array $filter the filter conditions including $id
Returns
string to be added to URL
Definition at line 622 of file plot_card.php.
References $filter.
Referenced by displayPlotTasks().
deletePlot (plot $object)
Delete selected plot from database.
! No control is made on plot use !
Parameters
plot $object
Definition at line 247 of file plot_card.php.
References $conf, $db, $langs, $result, $user, and plot\delete().
displayAddPlotForm (plot $object, ExtraFields $extrafields)
Display the form to enter a new plot.
Parameters
plot $object
ExtraFields $extrafields
Definition at line 156 of file plot_card.php.
References $_SERVER, $conf, $db, $langs, $user, and print.
displayPlotCard ($action, plot $object, ExtraFields $extrafields, Form $form)
Display the plot card in read mode.
When $action = delete a confirmation popup
Parameters
string $action
plot $object
ExtraFields $extrafields
Form $form
Definition at line 423 of file plot_card.php.
References $_SERVER, $action, $conf, $db, $langs, $parameters, $user, and print.
Referenced by displayPlotTab().
displayPlotEditForm (plot $object, ExtraFields $extrafields)
Display the Plot Edit Form.
Parameters
plot $object
ExtraFields $extrafields
Definition at line 327 of file plot_card.php.
References $_SERVER, $conf, $db, $langs, $user, and print.
displayPlotTab ($action, plot $object, ExtraFields $extrafields)
Display the proper Plot Tab based on the tab parameter usin GETPOST.
Support tabs : tasks, notes, info and card as default.
Parameters
string $action
plot $object
ExtraFields $extrafields
Definition at line 377 of file plot_card.php.
References $action, $conf, $db, $form, $formvignoble, $langs, $tab, $user, displayPlotCard(), displayPlotTasks(), getTabsHeader(), and plot\info().
displayPlotTaskLines ($plottask)
Display the plot task lines in a table in read only mode.
Each line display Task ref and label, note and coverage.
Parameters
$plottask the result of the SQL query on plot task
Definition at line 645 of file plot_card.php.
References $conf, $db, $langs, $user, and print.
Referenced by displayPlotTasks().
displayPlotTasks (plot $plot, Form $form)
Display the tasks table for the plot.
The table could be sorted and searched on all fields Search on date define an interval between start and end
Parameters
plot $plot
Form $form
Definition at line 467 of file plot_card.php.
References $_SERVER, $_SESSION, $action, $conf, $db, $filter, $langs, $sort, $user, buildTaskSearchParameters(), displayPlotTaskLines(), getTaskfilter(), getTasksort(), and print.
Referenced by displayPlotTab().
getTabsHeader ($langs, $object)
Set up the 4 Tabs : Card, Tasks, Notes, Info.
Parameters
plot $object
Definition at line 689 of file plot_card.php.
References $langs, and $object.
Referenced by displayPlotTab().
getTaskfilter ($id)
Get all data needed to filter the SQL requests on plot task and produce the results.
Parameters
int $id the current plot id
Returns
Array[] containing the following keys : id (of the task), reference (of the task), note, coverage, plot (array of sql filter conditions for plot task),
Definition at line 555 of file plot_card.php.
References $filter, and $id.
Referenced by displayPlotTasks().
getTasksort ()
Get fields and order used for the plot task table sort.
Use TaskRef Ascending by default.
Returns
Array[] with keys : field, order.
Definition at line 526 of file plot_card.php.
References $sort, $sortfield, and $sortorder.
Referenced by displayPlotTasks().
removePlotFile (plot $object)
Remove file associated to current object.
File id is provided in Get Post
Parameters
plot $object
Definition at line 303 of file plot_card.php.
References $conf, $db, $langs, and $user.
updatePlot (plot $object, ExtraFields $extrafields)
Update Plot information in database using the Plot Edit Form data.
Parameters
plot $object
ExtraFields $extrafields
Returns
string $action 'view' when update is done | 'edit' if fields are not properly entered
Definition at line 204 of file plot_card.php.
References $action, $conf, $db, $error, $langs, $result, $user, and plot\update().
Variable Documentation
$action = GETPOST('action', 'alpha')
Definition at line 35 of file plot_card.php.
Referenced by addPlot(), buildPlotDocument(), displayPlotCard(), displayPlotTab(), displayPlotTasks(), and updatePlot().
$cancel = GETPOST('cancel', 'alpha')
Definition at line 37 of file plot_card.php.
$confirm = GETPOST('confirm', 'alpha')
Definition at line 36 of file plot_card.php.
$extrafields = new ExtraFields($db)
Definition at line 46 of file plot_card.php.
Referenced by displayTaskCard(), displayTaskEditForm(), plot\fetch(), modVignoble\getExports(), modVignoble\getImports(), plot\loadObject(), and updateTask().
$id = GETPOST('id', 'int')
Definition at line 32 of file plot_card.php.
Referenced by addPlot(), and getTaskfilter().
$object = new plot($db)
Definition at line 45 of file plot_card.php.
Referenced by getTabsHeader().
$ref = GETPOST('ref', 'alpha')
Definition at line 33 of file plot_card.php.
$tab = GETPOST('tab', 'alpha')
Definition at line 38 of file plot_card.php.
Referenced by displayPlotTab().
if (($id > 0||!empty($ref))) else
Initial value:
{
    if (! $user->rights->vignoble->plot->create)
        accessforbidden()
Definition at line 86 of file plot_card.php.