Vignoble: lib/admin.html.lib.php File Reference
admin.html.lib.php File Reference
Administration
Module library for Admin Pages.
Functions
beginForm ($currentTab, $page_title="Vignoble Setup")
Display begining of card form including :
endForm ()
Perform all required operations to end properly a card form.
vignobleAdminPrepareTabs ()
Populate tabs array with all tabs for the admin page.
Detailed Description
Module library for Admin Pages.
Contains main components for admin pages
Definition in file admin.html.lib.php.
Function Documentation
beginForm ($currentTab, $page_title = "Vignoble Setup")
Display begining of card form including :
Dolibarr header,
Form title with modules link back
Tabs for administration
Parameters
string $currentTab The tab key of the tab to select/display
string $page_title The HTML page title common to all tabs
Definition at line 38 of file admin.html.lib.php.
References $conf, $db, $langs, $user, print, and vignobleAdminPrepareTabs().
Referenced by printView().
endForm ()
Perform all required operations to end properly a card form.
Definition at line 54 of file admin.html.lib.php.
References $conf, $db, and $langs.
Referenced by printView().
vignobleAdminPrepareTabs ()
Populate tabs array with all tabs for the admin page.
Returns
$tabs an array with one line per tab with on each line
full URL of the page for the tab
tab name to display (string)
tab key (string)
Definition at line 73 of file admin.html.lib.php.
References $conf, and $langs.
Referenced by beginForm().