Vignoble: cultivationtaskcontact.php File Reference
cultivationtaskcontact.php File Reference
Cultivation management
contacts for a cultivation project task
Functions
addTaskUser ($object, $projectstatic)
Add a user links to the task based on users selected in the add user form.
swapTaskUserStatus ($task)
Swap task user status from active to unactive or the other way.
deleteTaskUser ($task)
Remove user from task.
displayAddUserForm ($task, $projectstatic)
Display the add user form to associate one or more user to the task.
displayTaskUsers ($taskusers, $task)
Display the task user table with role and status.
Variables
$cultivationprojectid = setIsCultivationProject()
$id = GETPOST('id', 'int')
$ref = GETPOST('ref', 'alpha')
$action = GETPOST('action', 'alpha')
$confirm = GETPOST('confirm', 'alpha')
$cancel = GETPOST('cancel', 'alpha')
$object = new Task($db)
$projectstatic = new Project($db)
Detailed Description
contacts for a cultivation project task
Definition in file cultivationtaskcontact.php.
Function Documentation
addTaskUser ($object, $projectstatic)
Add a user links to the task based on users selected in the add user form.
Parameters
object the task
projectstatic The cultivation project
Definition at line 134 of file cultivationtaskcontact.php.
References $conf, $db, $error, $langs, $object, $result, $user, and get_dolusers().
deleteTaskUser ($task)
Remove user from task.
Parameters
$task the task object
Returns
string $action empty
Definition at line 199 of file cultivationtaskcontact.php.
References $action, $conf, $db, $error, $langs, $result, and $user.
displayAddUserForm ($task, $projectstatic)
Display the add user form to associate one or more user to the task.
Parameters
$task the current task object
$projectstatic the current project
Definition at line 222 of file cultivationtaskcontact.php.
References $_SERVER, $_SESSION, $conf, $db, $langs, $user, getProjectContributors(), and print.
displayTaskUsers ($taskusers, $task)
Display the task user table with role and status.
Parameters
array $taskusers contains the list of users
Task $task the current task
Definition at line 270 of file cultivationtaskcontact.php.
References $_SERVER, $conf, $db, $langs, $user, and print.
swapTaskUserStatus ($task)
Swap task user status from active to unactive or the other way.
Parameters
$task the current task
Definition at line 179 of file cultivationtaskcontact.php.
References $conf, $db, $error, $langs, $result, and $user.
Variable Documentation
$action = GETPOST('action', 'alpha')
Definition at line 34 of file cultivationtaskcontact.php.
Referenced by deleteTaskUser().
$cancel = GETPOST('cancel', 'alpha')
Definition at line 36 of file cultivationtaskcontact.php.
$confirm = GETPOST('confirm', 'alpha')
Definition at line 35 of file cultivationtaskcontact.php.
$cultivationprojectid = setIsCultivationProject()
Definition at line 28 of file cultivationtaskcontact.php.
$id = GETPOST('id', 'int')
Definition at line 31 of file cultivationtaskcontact.php.
$object = new Task($db)
Definition at line 42 of file cultivationtaskcontact.php.
Referenced by pdf_plotabc\_pagefoot(), pdf_plotabc\_pagehead(), pdf_plotabc\_tableau_info(), pdf_plotabc\_tableau_tot(), addPlotTask(), addTaskUser(), addTimeSpent(), Plotcultivationtask\createFromClone(), plot\createFromClone(), deleteTask(), deleteTimeSpent(), displayAddPlotForm(), displayAddTimeSpentForm(), displayProjectHeaderCard(), displayTaskHeader(), displayTaskTimeSpentLine(), ActionsVignoble\doActions(), getTaskTimeSpent(), FormVignoble\printObjectRef(), updatePlotTaskStatus(), updateTimeSpent(), and pdf_plotabc\write_file().
$projectstatic = new Project($db)
Definition at line 43 of file cultivationtaskcontact.php.
Referenced by getProjectContributors(), and showtasks().
$ref = GETPOST('ref', 'alpha')
Definition at line 32 of file cultivationtaskcontact.php.