Vignoble: plot Class Reference
plot Class Reference
Class plot.
Public Member Functions
__construct (DoliDB $db)
Constructor.
create (User $user, $notrigger=false)
Create object into database.
loadObject ($id, $ref=null, $force=false)
Load object in memory from the database.
fetch ($id, $ref=null)
Load object in memory from the database.
fetchAll ($sortorder= '', $sortfield= '', $limit=0, $offset=0, array $filter=array(), $filtermode= 'AND')
Load a set of objects in memory from the database.
update (User $user, $notrigger=false)
Update object into database.
delete (User $user, $notrigger=false)
Delete object in database.
createFromClone ($fromid)
Load an object from its id and create a new one in database.
getNomUrl ($withpicto=0, $option= '', $notooltip=0, $maxlen=24, $morecss= '')
Return a link to the user card (with optionaly the picto)
getLibStatut ($mode=0)
Retourne le libelle du status d'un user (actif, inactif)
LibStatut ($status, $mode=0)
Renvoi le libelle d'un status donne.
info ($id, $ref=null)
get object info
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0)
Create a document onto disk accordign to template module.
initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Public Attributes
$element = 'plot'
$table_element = 'plot'
$lines = array()
$entity = 1
$ref
$label
$description
$note_private
$note_public
$tms = ''
$datec = ''
$fk_user_author
$fk_user_modif
Detailed Description
Class plot.
Define the object and the CRUD methods and some more.
See also
CommonObject
Definition at line 40 of file plot.class.php.
Constructor & Destructor Documentation
plot::__construct (DoliDB $db)
Constructor.
Parameters
DoliDb $db Database handler
Definition at line 94 of file plot.class.php.
References $db.
Member Function Documentation
plot::create (User $user, $notrigger = false)
Create object into database.
Parameters
User $user User that creates
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, Id of created object if OK
Definition at line 110 of file plot.class.php.
References $conf, $error, $id, $resql, $result, and $sql.
Referenced by addPlot().
plot::createFromClone ($fromid)
Load an object from its id and create a new one in database.
Parameters
int $fromid Id of object to clone
Returns
int New id of clone
Definition at line 617 of file plot.class.php.
References $error, $object, $result, and $user.
plot::delete (User $user, $notrigger = false)
Delete object in database.
Parameters
User $user User that deletes
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 556 of file plot.class.php.
References $conf, $error, $id, $resql, $result, $sql, and $table_element.
Referenced by deletePlot().
plot::fetch ($id, $ref = null)
Load object in memory from the database.
Parameters
int $id Id object
string $ref Ref
Returns
int <0 if KO, 0 if not found, >0 if OK
Definition at line 307 of file plot.class.php.
References $extrafields, $id, $ref, $resql, and $sql.
plot::fetchAll ($sortorder = '', $sortfield = '', $limit = 0, $offset = 0, array $filter = array(), $filtermode = 'AND')
Load a set of objects in memory from the database.
Parameters
string $sortorder Sort Order
string $sortfield Sort field
int $limit offset limit
int $offset offset limit
array $filter filter array
string $filtermode filter mode (AND or OR)
Returns
int <0 if KO, >0 if OK
Definition at line 389 of file plot.class.php.
References $filter, $limit, $offset, $resql, $sortfield, $sortorder, $sql, and $value.
plot::generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0)
Create a document onto disk accordign to template module.
Parameters
string $modele Force le mnodele a utiliser ('' to not force)
Translate $outputlangs objet lang a utiliser pour traduction
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
Returns
int 0 if KO, 1 if OK
Definition at line 823 of file plot.class.php.
References $conf, and $langs.
Referenced by buildPlotDocument().
plot::getLibStatut ($mode = 0)
Retourne le libelle du status d'un user (actif, inactif)
Parameters
int $mode 0=libelle long, 1=libelle court, 2=Picto + Libelle court, 3=Picto, 4=Picto + Libelle long, 5=Libelle court + Picto
Returns
string Label of status
Definition at line 706 of file plot.class.php.
References $mode, and LibStatut().
plot::getNomUrl ($withpicto = 0, $option = '', $notooltip = 0, $maxlen = 24, $morecss = '')
Return a link to the user card (with optionaly the picto)
Parameters
int $withpicto Include picto in link (0=No picto, 1=Include picto into link, 2=Only picto)
string $option On what the link point to
integer $notooltip 1=Disable tooltip
int $maxlen Max length of visible user name
string $morecss Add more css on link
Returns
string String with URL
Definition at line 672 of file plot.class.php.
References $conf, $db, $label, $langs, $ref, and $result.
plot::info ($id, $ref = null)
get object info
Parameters
int $id Id of object
Returns
void
Definition at line 770 of file plot.class.php.
References $id, $ref, $result, and $sql.
Referenced by displayPlotTab().
plot::initAsSpecimen ()
Initialise object with example values Id must be 0 if object instance is a specimen.
Returns
void
Definition at line 849 of file plot.class.php.
plot::LibStatut ($status, $mode = 0)
Renvoi le libelle d'un status donne.
Parameters
int $status Id status
int $mode 0=libelle long, 1=libelle court, 2=Picto + Libelle court, 3=Picto, 4=Picto + Libelle long, 5=Libelle court + Picto
Returns
string Label of status
Definition at line 720 of file plot.class.php.
References $langs, and $mode.
Referenced by getLibStatut().
plot::loadObject ($id, $ref = null, $force = false)
Load object in memory from the database.
Parameters
int $id Object Id
string $ref Object Reference
$force True, force SELECT in DB when $this->id is not empty False, do not acces DB if $this-> id is not empty
Returns
int <0 if KO, 0 if not found, Id of object if OK
Definition at line 231 of file plot.class.php.
References $extrafields, $id, $ref, $resql, and $sql.
plot::update (User $user, $notrigger = false)
Update object into database.
Parameters
User $user User that modifies
bool $notrigger false=launch triggers after, true=disable triggers
Returns
int <0 if KO, >0 if OK
Definition at line 471 of file plot.class.php.
References $conf, $error, $id, $resql, $result, and $sql.
Referenced by updatePlot().
Member Data Documentation
plot::$datec = ''
Definition at line 79 of file plot.class.php.
plot::$description
Definition at line 71 of file plot.class.php.
plot::$element = 'plot'
Definition at line 47 of file plot.class.php.
plot::$entity = 1
Definition at line 65 of file plot.class.php.
plot::$fk_user_author
Definition at line 81 of file plot.class.php.
plot::$fk_user_modif
Definition at line 83 of file plot.class.php.
plot::$label
Definition at line 69 of file plot.class.php.
Referenced by getNomUrl().
plot::$lines = array()
Definition at line 59 of file plot.class.php.
plot::$note_private
Definition at line 73 of file plot.class.php.
plot::$note_public
Definition at line 75 of file plot.class.php.
plot::$ref
Definition at line 67 of file plot.class.php.
Referenced by fetch(), getNomUrl(), info(), and loadObject().
plot::$table_element = 'plot'
Definition at line 53 of file plot.class.php.
Referenced by delete().
plot::$tms = ''
Definition at line 77 of file plot.class.php.
The documentation for this class was generated from the following file:
class/plot.class.php