Vignoble: admin/module_settings.php File Reference
module_settings.php File Reference
Functions
printDocumentModelView ($dirmodels)
Generate and print the document model view.
prepareDocumentModel ($action, $value, $label, $type, $scandir)
prepare Document Model Actions
Variables
if(!$user->admin) $action = GETPOST('action', 'alpha')
$value = GETPOST('value', 'alpha')
$label = GETPOST('label', 'alpha')
$scandir = GETPOST('scandir', 'alpha')
$type = 'plot'
if($action) $form = new Form($db)
Process actions.
print $_SERVER ['PHP_SELF']
print $_SESSION ['newtoken']
print
print n
$rowspan = 1
if(!empty($conf->global->VIGNOBLE_CULTIVATIONPROJECT)) $project = new Project($db)
$select_projects = $project->liste_array()
Function Documentation
prepareDocumentModel ($action, $value, $label, $type, $scandir)
prepare Document Model Actions
Process Actions
specimen : define a pdf specimen document
set : activate a document model
del : delete a document model
setdoc : set a default document model
Display document model view
Definition at line 283 of file module_settings.php.
References $action, $conf, $db, $label, $langs, $plot, $scandir, $type, $user, and $value.
printDocumentModelView ($dirmodels)
Generate and print the document model view.
Definition at line 130 of file module_settings.php.
References $_SERVER, $conf, $db, $form, $langs, $resql, $sql, $type, $user, and print.
Variable Documentation
print $_SERVER['PHP_SELF']
Definition at line 91 of file module_settings.php.
Referenced by displayTable(), displayTaskEditForm(), printButtonNewField(), and printDocumentModelView().
print $_SESSION['newtoken']
Definition at line 92 of file module_settings.php.
Referenced by displaySearchForm(), and displayTaskEditForm().
if (!$user->admin) $action = GETPOST('action', 'alpha')
Definition at line 47 of file module_settings.php.
Referenced by prepareDocumentModel().
if ($action) $form = new Form($db)
Process actions.
Display parameters
Definition at line 85 of file module_settings.php.
Referenced by printDocumentModelView().
$label = GETPOST('label', 'alpha')
Definition at line 49 of file module_settings.php.
Referenced by getTaskUrl(), and prepareDocumentModel().
if (!empty($conf->global->VIGNOBLE_CULTIVATIONPROJECT)) $project = new Project($db)
Definition at line 105 of file module_settings.php.
print $rowspan = 1
Definition at line 101 of file module_settings.php.
$scandir = GETPOST('scandir', 'alpha')
Definition at line 50 of file module_settings.php.
Referenced by prepareDocumentModel().
$select_projects = $project->liste_array()
Definition at line 107 of file module_settings.php.
$type = 'plot'
Definition at line 52 of file module_settings.php.
Referenced by ModelePDFPlot\liste_modeles(), ModeleVignoble\liste_modeles(), prepareDocumentModel(), and printDocumentModelView().
$value = GETPOST('value', 'alpha')
Definition at line 48 of file module_settings.php.
Referenced by plot\fetchAll(), modVignoble\getImports(), and prepareDocumentModel().
print n
Definition at line 99 of file module_settings.php.
print
Definition at line 93 of file module_settings.php.
Referenced by printDocumentModelView().