Vignoble: ordersandshipments.php File Reference
ordersandshipments.php File Reference
Dashboard
Displays products orders and shipments numbers between 2 dates.
Functions
displayView ($orders, $shipments, $sort, $filter)
Displays the page view.
displaySearchForm ($filter, $sort)
Display the filter Form :
displayTable ($tablename, $table, $sort, $urlparam)
Display the result table :
getsort ()
Get field and order used for the tables sort.
getfilter ()
Get all data needed to filter the SQL requests and produce the results.
buildSearchParameters ($filter)
Build the parameters string to be added to URL to keep the filter conditions.
Variables
if(!(!empty($conf->product->enabled)&&$user->rights->produit->lire)) $sort = getsort()
$filter = getfilter()
$orderlines = fetchProductsOrders($sort, '', '', $filter["orders"], 'AND')
$shipmentlines = fetchProductsShipments($sort, '', '', $filter["shipments"], 'AND')
Detailed Description
Displays products orders and shipments numbers between 2 dates.
Definition in file ordersandshipments.php.
Function Documentation
buildSearchParameters ($filter)
Build the parameters string to be added to URL to keep the filter conditions.
(used for list sort)
Parameters
Array $filter the filter conditions
Returns
string to be added to URL
Definition at line 301 of file ordersandshipments.php.
References $filter.
Referenced by displayView().
displaySearchForm ($filter, $sort)
Display the filter Form :
Date begin, date end, products list.
Parameters
array[] $filter the filter parameters
array[] $sort sort field and order
Definition at line 110 of file ordersandshipments.php.
References $_SESSION, $conf, $db, $filter, $form, $langs, $sort, $user, fetchProducts(), and print.
Referenced by displayView().
displayTable ($tablename, $table, $sort, $urlparam)
Display the result table :
Product ref, product label, object count, quantity, amount
Parameters
string $tablename name of the object
array[] $table result set from SQL query
array[] $sort sort field and order
string $urlparam filter parameters as a URL part for field sort
Definition at line 157 of file ordersandshipments.php.
References $_SERVER, $conf, $db, $langs, $sort, $user, and print.
Referenced by displayView().
displayView ($orders, $shipments, $sort, $filter)
Displays the page view.
A filter form to select date begin, date end, products. Then Orders and Shipment summary by products on 2 columns.
Parameters
array[] $orders the orders summary result set
array[] $shipments the shipments summary result set
array[] $sort sort field and order
array[] $filter the filter parameters
Definition at line 69 of file ordersandshipments.php.
References $conf, $db, $filter, $langs, $sort, $user, buildSearchParameters(), displaySearchForm(), displayTable(), and print.
getfilter ()
Get all data needed to filter the SQL requests and produce the results.
Returns
Array[] containing the following keys : datebegin, dateend, products (array of selected products), orders (array of sql filter conditions for orders), shipments (array of sql filter conditions for shipments),
Definition at line 243 of file ordersandshipments.php.
References $filter.
getsort ()
Get field and order used for the tables sort.
Use Ref Ascending by default.
Returns
Array[] with keys : field, order.
Definition at line 217 of file ordersandshipments.php.
References $sort, $sortfield, and $sortorder.
Variable Documentation
$filter = getfilter()
Definition at line 44 of file ordersandshipments.php.
Referenced by buildSearchParameters(), displaySearchForm(), displayView(), Plotcultivationtask\fetchAll(), plot\fetchAll(), fetchProductsOrders(), fetchProductsShipments(), and getfilter().
$orderlines = fetchProductsOrders($sort, '', '', $filter["orders"], 'AND')
Definition at line 46 of file ordersandshipments.php.
$shipmentlines = fetchProductsShipments($sort, '', '', $filter["shipments"], 'AND')
Definition at line 48 of file ordersandshipments.php.
if (!(!empty($conf->product->enabled)&&$user->rights->produit->lire)) $sort = getsort()
Definition at line 42 of file ordersandshipments.php.
Referenced by displaySearchForm(), displayTable(), displayView(), fetchProductsOrders(), fetchProductsShipments(), and getsort().