Vignoble: plot_info.php File Reference
plot_info.php File Reference
Plot Management
The plot info tab.
Variables
$id = GETPOST("id", 'int')
$ref = GETPOST("ref", 'alpha')
if ($ref== '') = $db->plimit($conf->liste_limit + 1, $offset)
$form = new Form($db)
$formvignoble = new FormVignoble($db)
$currentPlot = new plot($db)
$head = $formvignoble->getTabsHeader($langs, $currentPlot)
print
Detailed Description
The plot info tab.
The form displays the user information associated to the object. User attributes are in view mode only. Top of the form is standardised to display the object identity and navigate the object list.
Definition in file plot_info.php.
Variable Documentation
$currentPlot = new plot($db)
Definition at line 62 of file plot_info.php.
$form = new Form($db)
Definition at line 59 of file plot_info.php.
$formvignoble = new FormVignoble($db)
Definition at line 60 of file plot_info.php.
$head = $formvignoble->getTabsHeader($langs, $currentPlot)
Definition at line 69 of file plot_info.php.
Referenced by FormVignoble\getTabsHeader(), printView(), and vignobleAdminPrepareHead().
$id = GETPOST("id", 'int')
Definition at line 45 of file plot_info.php.
$ref = GETPOST("ref", 'alpha')
Definition at line 46 of file plot_info.php.
* if = $db->plimit($conf->liste_limit + 1, $offset)
Definition at line 47 of file plot_info.php.
print
Definition at line 73 of file plot_info.php.
Referenced by addJQuery(), displayView(), FormVignoble\printObjectRef(), and printView().