Vignoble: plot_notes.php File Reference
plot_notes.php File Reference
Plot Management
The plot note form.
Variables
$id = GETPOST('id', 'int')
$ref = GETPOST('ref', 'alpha')
$action = GETPOST('action', 'alpha')
$object = new plot($db)
$result = $object->loadObject($id, $ref, true)
$permission = true
$permissionnote = true
$form = new Form($db)
$formvignoble = new FormVignoble($db)
Detailed Description
The plot note form.
The form displays the notes (public and private) of the plot. Notes are in view mode first. The user could use the form to update, create or delete a note. Top of the form is standardised to display the object identity and navigate the object list.
Definition in file plot_notes.php.
Variable Documentation
$action = GETPOST('action', 'alpha')
Definition at line 43 of file plot_notes.php.
$form = new Form($db)
Definition at line 72 of file plot_notes.php.
$formvignoble = new FormVignoble($db)
Definition at line 73 of file plot_notes.php.
$id = GETPOST('id', 'int')
Definition at line 41 of file plot_notes.php.
$object = new plot($db)
Definition at line 51 of file plot_notes.php.
$permission = true
Definition at line 57 of file plot_notes.php.
$permissionnote = true
Definition at line 58 of file plot_notes.php.
$ref = GETPOST('ref', 'alpha')
Definition at line 42 of file plot_notes.php.
$result = $object->loadObject($id, $ref, true)
Definition at line 52 of file plot_notes.php.
Referenced by plot\create(), createDefaultFields(), plot\createFromClone(), plot\delete(), plot\getNomUrl(), plot\info(), modVignoble\init(), and plot\update().