Vignoble: admin/about.php File Reference
about.php File Reference
Displays module information in a Setup Tab Tab content :
Variables
if(false===(@include '../../main.inc.php')) global $langs
if(false===(@include '../../main.inc.php')) global $user
if(!$user->admin) $action = GETPOST('action', 'alpha')
$page_name = "vignobleSetup"
$linkback = '<a href="' . DOL_URL_ROOT . '/admin/modules.php">' . $langs->trans("BackToModuleList") . '</a>'
$head = vignobleAdminPrepareHead()
switch ($langs->getDefaultLang())
dol_buildpath('/vignoble/COPYING', 1). '">' dol_buildpath ('/vignoble/img/gplv3.png', 1). '"/>'
Detailed Description
Displays module information in a Setup Tab Tab content :
README.md file for the module
COPYING file for the module
GPLV3 licence link
Definition in file about.php.
Variable Documentation
if (!$user->admin) $action = GETPOST('action', 'alpha')
Definition at line 55 of file about.php.
$head = vignobleAdminPrepareHead()
Definition at line 73 of file about.php.
if (false===(@include '../../main.inc.php')) global $langs
Definition at line 31 of file about.php.
Referenced by modVignoble\__construct(), pdf_plotabc\__construct(), plotsummarybox\__construct(), mybox\__construct(), pdf_plotabc\_pagehead(), ActionsVignoble\addSearchEntry(), defineListFields(), FormVignoble\displayDicCombo(), displayView(), plot\generateDocument(), ModeleNumRefCommandes\getExample(), ModeleNumRefCommandes\getNextValue(), plot\getNomUrl(), FormVignoble\getTabsHeader(), ModeleNumRefCommandes\getVersion(), ModeleNumRefCommandes\info(), plot\LibStatut(), plotsummarybox\loadBox(), mybox\loadBox(), FormVignoble\printObjectRef(), vignobleAdminPrepareHead(), and pdf_plotabc\write_file().
$linkback = '<a href="' . DOL_URL_ROOT . '/admin/modules.php">' . $langs->trans("BackToModuleList") . '</a>'
Definition at line 69 of file about.php.
Referenced by FormVignoble\printObjectRef(), and printView().
$page_name = "vignobleSetup"
Definition at line 65 of file about.php.
Referenced by printView().
if (false===(@include '../../main.inc.php')) global $user
Definition at line 31 of file about.php.
Referenced by plot\createFromClone(), FormVignoble\displayDicCombo(), displayView(), and pdf_plotabc\write_file().
dol_buildpath ('/vignoble/COPYING', 1). '">' dol_buildpath('/vignoble/img/gplv3.png', 1). '"/>'
Definition at line 91 of file about.php.
Referenced by ActionsVignoble\addSearchEntry(), plot\getNomUrl(), FormVignoble\printObjectRef(), printView(), and vignobleAdminPrepareHead().
switch($langs->getDefaultLang())
Definition at line 82 of file about.php.