Vignoble: pdf_plotabc Class Reference
pdf_plotabc Class Reference
Classe to generate PDF orders with template Plot.
Public Member Functions
__construct ($db)
Constructor.
write_file ($object, $outputlangs, $srctemplatepath='', $hidedetails=0, $hidedesc=0, $hideref=0)
Function to build pdf onto disk.
_tableau_versements (&$pdf, $object, $posy, $outputlangs)
Show payments table.
_tableau_info (&$pdf, $object, $posy, $outputlangs)
Show miscellaneous information (payment mode, payment term, ...)
_tableau_tot (&$pdf, $object, $deja_regle, $posy, $outputlangs)
Show total to pay.
_tableau (&$pdf, $tab_top, $tab_height, $nexY, $outputlangs, $hidetop=0, $hidebottom=0, $currency='')
Show table for lines.
_pagehead (&$pdf, $object, $showaddress, $outputlangs, $titlekey="Order")
Show top header of page.
_pagefoot (&$pdf, $object, $outputlangs, $hidefreetext=0)
Show footer of page.
Public Attributes
$db
$name
$description
$type
$phpmin = array(4,3,0)
$version = 'dolibarr'
$page_largeur
$page_hauteur
$format
$marge_gauche
$marge_droite
$marge_haute
$marge_basse
$emetteur
Public Attributes inherited from ModelePDFPlot
$error =''
Additional Inherited Members
Static Public Member Functions inherited from ModelePDFPlot
static liste_modeles ($db, $maxfilenamelength=0)
Return list of active generation modules.
Detailed Description
Classe to generate PDF orders with template Plot.
Definition at line 41 of file pdf_plotabc.modules.php.
Constructor & Destructor Documentation
pdf_plotabc::__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Definition at line 67 of file pdf_plotabc.modules.php.
References $conf, $db, and $langs.
Member Function Documentation
pdf_plotabc::_pagefoot (& $pdf, $object, $outputlangs, $hidefreetext = 0)
Show footer of page.
Need this->emetteur object
Parameters
TCPDF $pdf PDF
Object $object Object to show
Translate $outputlangs Object lang for output
int $hidefreetext 1=Hide free text
Returns
int Return height of bottom margin including footer text
Definition at line 1139 of file pdf_plotabc.modules.php.
References $conf, and $object.
Referenced by write_file().
pdf_plotabc::_pagehead (& $pdf, $object, $showaddress, $outputlangs, $titlekey = "Order")
Show top header of page.
Parameters
TCPDF $pdf Object PDF
Object $object Object to show
int $showaddress 0=no, 1=yes
Translate $outputlangs Object lang for output
string $titlekey Translation key to show as title of document
Returns
void
Definition at line 948 of file pdf_plotabc.modules.php.
References $conf, $langs, $marge_gauche, $marge_haute, $object, and $title.
Referenced by write_file().
pdf_plotabc::_tableau (& $pdf, $tab_top, $tab_height, $nexY, $outputlangs, $hidetop = 0, $hidebottom = 0, $currency = '')
Show table for lines.
Parameters
TCPDF $pdf Object PDF
string $tab_top Top position of table
string $tab_height Height of table (rectangle)
int $nexY Y (not used)
Translate $outputlangs Langs object
int $hidetop 1=Hide top bar of array and title, 0=Hide nothing, -1=Hide only title
int $hidebottom Hide bottom bar of array
string $currency Currency code
Returns
void
Definition at line 838 of file pdf_plotabc.modules.php.
References $conf.
pdf_plotabc::_tableau_info (& $pdf, $object, $posy, $outputlangs)
Show miscellaneous information (payment mode, payment term, ...)
Parameters
TCPDF $pdf Object PDF
Object $object Object to show
int $posy Y
Translate $outputlangs Langs object
Returns
void
Definition at line 389 of file pdf_plotabc.modules.php.
References $conf, $marge_gauche, and $object.
pdf_plotabc::_tableau_tot (& $pdf, $object, $deja_regle, $posy, $outputlangs)
Show total to pay.
Parameters
TCPDF $pdf Object PDF
Facture $object Object invoice
int $deja_regle Montant deja regle
int $posy Position depart
Translate $outputlangs Objet langs
Returns
int Position pour suite
Definition at line 576 of file pdf_plotabc.modules.php.
References $conf, and $object.
pdf_plotabc::_tableau_versements (& $pdf, $object, $posy, $outputlangs)
Show payments table.
Parameters
TCPDF $pdf Object PDF
Object $object Object order
int $posy Position y in PDF
Translate $outputlangs Object langs for output
Returns
int <0 if KO, >0 if OK
Definition at line 374 of file pdf_plotabc.modules.php.
pdf_plotabc::write_file ($object, $outputlangs, $srctemplatepath = '', $hidedetails = 0, $hidedesc = 0, $hideref = 0)
Function to build pdf onto disk.
Parameters
Object $object Object to generate
Translate $outputlangs Lang output object
string $srctemplatepath Full path of source filename for generator using a template file
int $hidedetails Do not show line details
int $hidedesc Do not show desc
int $hideref Do not show ref
Returns
int 1=OK, 0=KO
Definition at line 154 of file pdf_plotabc.modules.php.
References $action, $conf, $db, $langs, $object, $parameters, $reshook, $user, _pagefoot(), and _pagehead().
Member Data Documentation
pdf_plotabc::$db
Definition at line 43 of file pdf_plotabc.modules.php.
Referenced by __construct(), and write_file().
pdf_plotabc::$description
Definition at line 45 of file pdf_plotabc.modules.php.
pdf_plotabc::$emetteur
Definition at line 59 of file pdf_plotabc.modules.php.
pdf_plotabc::$format
Definition at line 53 of file pdf_plotabc.modules.php.
pdf_plotabc::$marge_basse
Definition at line 57 of file pdf_plotabc.modules.php.
pdf_plotabc::$marge_droite
Definition at line 55 of file pdf_plotabc.modules.php.
pdf_plotabc::$marge_gauche
Definition at line 54 of file pdf_plotabc.modules.php.
Referenced by _pagehead(), and _tableau_info().
pdf_plotabc::$marge_haute
Definition at line 56 of file pdf_plotabc.modules.php.
Referenced by _pagehead().
pdf_plotabc::$name
Definition at line 44 of file pdf_plotabc.modules.php.
pdf_plotabc::$page_hauteur
Definition at line 52 of file pdf_plotabc.modules.php.
pdf_plotabc::$page_largeur
Definition at line 51 of file pdf_plotabc.modules.php.
pdf_plotabc::$phpmin = array(4,3,0)
Definition at line 48 of file pdf_plotabc.modules.php.
pdf_plotabc::$type
Definition at line 46 of file pdf_plotabc.modules.php.
pdf_plotabc::$version = 'dolibarr'
Definition at line 49 of file pdf_plotabc.modules.php.
The documentation for this class was generated from the following file:
core/modules/vignoble/doc/pdf_plotabc.modules.php