Vignoble: cultivationtasktime.php File Reference
cultivationtasktime.php File Reference
Cultivation management
time spend by users for a cultivation project task allows to capture also plot status for the task
Functions
addTimeSpent ($object)
Add a time spent record for a task.
updateTimeSpent ($object)
update time spent of task using time spent form data
deleteTimeSpent ($object)
Delete the time spent line selected.
displayAddTimeSpentForm ($object, Form $form, $formother)
Display the add time spent form to add one or more line of time spent.
getTaskTimeSpent ($object, $sort, $filter)
get the Task time spent lines making the proper SQL request.
displayTaskTimeSpentLine ($task_time, $action, $object, Form $form, User $userstatic, $totalarray)
Display a task time spent line.
displayTaskTimeSpentTotal ($totalarray)
Display the time spent total line.
getsort ()
Get fields and order used for table sort.
getTimeSpentfilter ($id)
Get all data needed to filter the SQL requests on time spent task and produce the results.
buildTimeSpentSearchParameters ($filter)
Build the parameters string to be added to URL to keep the filter conditions.
displayPlotTaskLinesForm (FormOther $formother, Task $object)
Display the plot task lines in a form with the capability to edit all lines.
updatePlotTaskStatus ($object)
Update all plot status and note for the task using the add time form sub part regardint the plots.
Variables
$cultivationprojectid = setIsCultivationProject()
$id = GETPOST('id', 'int')
$ref = GETPOST('ref', 'alpha')
$action = GETPOST('action', 'alpha')
$confirm = GETPOST('confirm', 'alpha')
$cancel = GETPOST('cancel', 'alpha')
Detailed Description
time spend by users for a cultivation project task allows to capture also plot status for the task
Definition in file cultivationtasktime.php.
Function Documentation
addTimeSpent ($object)
Add a time spent record for a task.
Parameters
Task $object the current task
Returns
string $action empty
Definition at line 163 of file cultivationtasktime.php.
References $action, $conf, $db, $error, $langs, $object, $result, $user, and get_dolusers().
buildTimeSpentSearchParameters ($filter)
Build the parameters string to be added to URL to keep the filter conditions.
(used for list sort)
Parameters
Array $filter the filter conditions including $id
Returns
string to be added to URL
Definition at line 682 of file cultivationtasktime.php.
References $filter.
deleteTimeSpent ($object)
Delete the time spent line selected.
Parameters
Task $object the current task
Returns
string $action empty
Definition at line 301 of file cultivationtasktime.php.
References $action, $conf, $db, $langs, $object, $result, and $user.
displayAddTimeSpentForm ($object, Form $form, $formother)
Display the add time spent form to add one or more line of time spent.
One line is created by contributor.
Parameters
Task $object the current task
Form $form
FormOther $formother
Definition at line 327 of file cultivationtasktime.php.
References $_SERVER, $_SESSION, $conf, $db, $formother, $langs, $object, $user, displayPlotTaskLinesForm(), and getProjectContributors().
displayPlotTaskLinesForm (FormOther $formother, Task $object)
Display the plot task lines in a form with the capability to edit all lines.
Each line display plot ref and label, note and coverage.
Parameters
formother needed to use the select a percentage control
Task $object the current task result of the SQL query on plot task
Definition at line 709 of file cultivationtasktime.php.
References $conf, $db, $langs, $plot, and $user.
Referenced by displayAddTimeSpentForm().
displayTaskTimeSpentLine ($task_time, $action, $object, Form $form, User $userstatic, $totalarray)
Display a task time spent line.
Parameters
object $task_time the line to print
string $action when value is 'editline' the corresponding line is in edit mode
Task $object the current task
Form $form
User $userstatic
array $totalarray
Returns
array $totalarray the total fields and value
Definition at line 477 of file cultivationtasktime.php.
References $_SERVER, $action, $conf, $db, $langs, $object, and $user.
displayTaskTimeSpentTotal ($totalarray)
Display the time spent total line.
Parameters
array $totalarray containing the fields with total
Definition at line 576 of file cultivationtasktime.php.
References $conf, $db, $langs, and $user.
getsort ()
Get fields and order used for table sort.
Use Ref Ascending by default.
Returns
Array[] with keys : field, order.
Definition at line 603 of file cultivationtasktime.php.
References $sortfield, and $sortorder.
getTaskTimeSpent ($object, $sort, $filter)
get the Task time spent lines making the proper SQL request.
Parameters
Task $object the current task
array $sort the sort fields and order
array $filter the conditions to apply to get the lines
Returns
Object[] the time spent lines |NULL if empty
Definition at line 414 of file cultivationtasktime.php.
References $conf, $db, $filter, $langs, $object, $resql, $sql, and $user.
getTimeSpentfilter ($id)
Get all data needed to filter the SQL requests on time spent task and produce the results.
Parameters
int $id the current task id
Returns
Array[] containing the following keys : id (of the task), date of the time spent, user i.e. the contributor, note, timespent (array of sql filter conditions for time spent on task),
Definition at line 632 of file cultivationtasktime.php.
References $filter, and $id.
updatePlotTaskStatus ($object)
Update all plot status and note for the task using the add time form sub part regardint the plots.
Parameters
Task $object the current task
Returns
string
Definition at line 761 of file cultivationtasktime.php.
References $action, $conf, $db, $langs, $object, $result, and $user.
updateTimeSpent ($object)
update time spent of task using time spent form data
Parameters
Task $object the current task
Returns
string $action empty
Definition at line 256 of file cultivationtasktime.php.
References $action, $conf, $db, $error, $id, $langs, $object, $ref, $result, and $user.
Variable Documentation
$action = GETPOST('action', 'alpha')
Definition at line 35 of file cultivationtasktime.php.
Referenced by addTimeSpent(), deleteTimeSpent(), displayTaskTimeSpentLine(), updatePlotTaskStatus(), and updateTimeSpent().
$cancel = GETPOST('cancel', 'alpha')
Definition at line 37 of file cultivationtasktime.php.
$confirm = GETPOST('confirm', 'alpha')
Definition at line 36 of file cultivationtasktime.php.
$cultivationprojectid = setIsCultivationProject()
Definition at line 29 of file cultivationtasktime.php.
$id = GETPOST('id', 'int')
Definition at line 32 of file cultivationtasktime.php.
Referenced by getTimeSpentfilter(), and updateTimeSpent().
$ref = GETPOST('ref', 'alpha')
Definition at line 33 of file cultivationtasktime.php.
Referenced by updateTimeSpent().