Vignoble: plot_list.php File Reference
plot_list.php File Reference
Plot management
Display the list of plots.
Functions
defineListFields ($langs, $extrafields)
Return array of fields that are part of the list each field is identified by table field name field properties are stored in a sub array with label => display the user field name checked => [1 field displayed in list | 0 hidden] enabled => [ NULL or 1 field is usable| 0 field not usable] position => int to order the column.
addJQuery ()
Example : Adding jquery code.
Variables
$id = GETPOST('id', 'int')
$action = GETPOST('action', 'alpha')
$backtopage = GETPOST('backtopage')
$myparam = GETPOST('myparam', 'alpha')
$search_ref = GETPOST('search_ref', 'alpha')
$search_label = GETPOST('search_label', 'alpha')
$search_description = GETPOST('search_description', 'alpha')
$search_all = GETPOST('sall', 'alpha')
$optioncss = GETPOST('optioncss', 'alpha')
$limit = GETPOST("limit") ? GETPOST("limit", "int") : $conf->liste_limit
$sortfield = GETPOST('sortfield', 'alpha')
$sortorder = GETPOST('sortorder', 'alpha')
$page = GETPOST('page', 'int')
if($page==-1) $offset = $limit * $page
$pageprev = $page - 1
$pagenext = $page + 1
$socid = 0
$extrafields = new ExtraFields($db)
$extrafieldslabels = $extrafields->fetch_name_optionals_label('plot')
$search_array_extrafields = $extrafields->getOptionalsFromPost($extrafieldslabels, '', 'search_')
$fieldstosearchall
$arrayfields = defineListFields($langs, $extrafields)
$parameters = array()
ACTIONS
$reshook = $hookmanager->executeHooks('doActions', $parameters, $currentPlot, $action)
$form = new Form($db)
$formvignoble = new FormVignoble($db)
$plot = new plot($db)
$title = $langs->trans('PlotsList')
$sql = "SELECT"
$nbtotalofrecords = 0
$resql = $db->query($sql)
if($resql) else
Detailed Description
Display the list of plots.
The list of plots is paginated and could be filtered/search/sorted on displayed fields. User could select which fields to display in list. Each item of the list is selectable and link to the object form
Definition in file plot_list.php.
Function Documentation
addJQuery ()
Example : Adding jquery code.
Definition at line 576 of file plot_list.php.
References print.
defineListFields ($langs, $extrafields)
Return array of fields that are part of the list each field is identified by table field name field properties are stored in a sub array with label => display the user field name checked => [1 field displayed in list | 0 hidden] enabled => [ NULL or 1 field is usable| 0 field not usable] position => int to order the column.
Definition at line 529 of file plot_list.php.
References $arrayfields, $conf, $extrafields, and $langs.
Variable Documentation
$action = GETPOST('action', 'alpha')
Definition at line 52 of file plot_list.php.
$arrayfields = defineListFields($langs, $extrafields)
Definition at line 115 of file plot_list.php.
Referenced by defineListFields().
$backtopage = GETPOST('backtopage')
Definition at line 53 of file plot_list.php.
$extrafields = new ExtraFields($db)
Definition at line 96 of file plot_list.php.
Referenced by defineListFields().
$extrafieldslabels = $extrafields->fetch_name_optionals_label('plot')
Definition at line 98 of file plot_list.php.
$fieldstosearchall
Initial value:
= array(
    't.ref' => 'Ref',
    't.label' => 'Label',
    't.description' => 'Description'
)
Definition at line 105 of file plot_list.php.
$form = new Form($db)
Definition at line 170 of file plot_list.php.
$formvignoble = new FormVignoble($db)
Definition at line 171 of file plot_list.php.
$id = GETPOST('id', 'int')
Definition at line 51 of file plot_list.php.
$limit = GETPOST("limit") ? GETPOST("limit", "int") : $conf->liste_limit
Definition at line 66 of file plot_list.php.
$myparam = GETPOST('myparam', 'alpha')
Definition at line 54 of file plot_list.php.
$nbtotalofrecords = 0
Definition at line 243 of file plot_list.php.
if ($page==-1) $offset = $limit * $page
Definition at line 73 of file plot_list.php.
$optioncss = GETPOST('optioncss', 'alpha')
Definition at line 63 of file plot_list.php.
$page = GETPOST('page', 'int')
Definition at line 69 of file plot_list.php.
$pagenext = $page + 1
Definition at line 75 of file plot_list.php.
$pageprev = $page - 1
Definition at line 74 of file plot_list.php.
foreach ($search_array_extrafields as $key=> $val) $parameters = array()
ACTIONS
Put here all code to do according to value of "action" parameter
Definition at line 125 of file plot_list.php.
$plot = new plot($db)
Definition at line 172 of file plot_list.php.
Referenced by plotslastchanged\loadBox(), and prepareDocumentModel().
$reshook = $hookmanager->executeHooks('doActions', $parameters, $currentPlot, $action)
Definition at line 126 of file plot_list.php.
$resql = $db->query($sql)
Definition at line 256 of file plot_list.php.
Referenced by Plotcultivationtask\create(), plot\create(), Plotcultivationtask\delete(), plot\delete(), FormVignoble\displayDicCombo(), Plotcultivationtask\fetch(), plot\fetch(), Plotcultivationtask\fetchAll(), plot\fetchAll(), modVignoble\getImports(), Plotcultivationtask\loadObject(), plot\loadObject(), printDocumentModelView(), Plotcultivationtask\update(), and plot\update().
$search_all = GETPOST('sall', 'alpha')
Definition at line 61 of file plot_list.php.
$search_array_extrafields = $extrafields->getOptionalsFromPost($extrafieldslabels, '', 'search_')
Definition at line 99 of file plot_list.php.
$search_description = GETPOST('search_description', 'alpha')
Definition at line 59 of file plot_list.php.
$search_label = GETPOST('search_label', 'alpha')
Definition at line 58 of file plot_list.php.
$search_ref = GETPOST('search_ref', 'alpha')
Definition at line 57 of file plot_list.php.
$socid = 0
Definition at line 82 of file plot_list.php.
$sortfield = GETPOST('sortfield', 'alpha')
Definition at line 67 of file plot_list.php.
$sortorder = GETPOST('sortorder', 'alpha')
Definition at line 68 of file plot_list.php.
if (empty($conf->global->MAIN_DISABLE_FULL_SCANLIST)) $sql = "SELECT"
Definition at line 179 of file plot_list.php.
Referenced by Plotcultivationtask\create(), plot\create(), Plotcultivationtask\delete(), plot\delete(), FormVignoble\displayDicCombo(), Plotcultivationtask\fetch(), plot\fetch(), Plotcultivationtask\fetchAll(), plot\fetchAll(), fetchProducts(), fetchProductsOrders(), fetchProductsShipments(), modVignoble\getImports(), Plotcultivationtask\info(), plot\info(), modVignoble\init(), Plotcultivationtask\loadObject(), plot\loadObject(), printDocumentModelView(), modVignoble\remove(), Plotcultivationtask\update(), and plot\update().
$title = $langs->trans('PlotsList')
Definition at line 175 of file plot_list.php.
if ($resql) else
Initial value:
{
    $error ++
Definition at line 511 of file plot_list.php.