Vignoble: modVignoble Class Reference
modVignoble Class Reference
Description and activation class for module Vignoble.
Public Member Functions
__construct ($db)
Constructor.
init ($options= '')
Function called when module is enabled.
remove ($options= '')
Function called when module is disabled.
Private Member Functions
getDataDirectories ()
Get custom data directories in document folder.
getConfigPages ()
Get the configuration pages url stored in config_page_url array.
getDependencies ()
Get dependencies attributes and arrays for the module.
getLanguageFiles ()
Get module langage files url stored in langfiles array.
getTabs ()
Get module tabs stored in tabs array.
getPermissions ()
Get module permissions stored in rights array.
getMenuEntries ()
Get module menu entries stored in a menu array.
getExports ()
Get exports available for the module.
getConstant ()
Get list of custom constants from const array.
getParts ()
Get module parts array.
getBoxes ()
Get module boxes array.
getDictionaries ($conf)
Get module tables using the Dolibarr dictionary.
loadTables ()
Create tables, keys and data required by module Files llx_table1.sql, llx_table1.key.sql llx_data.sql with create table, create keys and create data commands must be stored in directory /vignoble/sql/ This function is called by this->init.
getImports ()
Get imports available for the module.
Detailed Description
Description and activation class for module Vignoble.
Definition at line 58 of file modVignoble.class.php.
Constructor & Destructor Documentation
modVignoble::__construct ($db)
Constructor.
Define names, constants, directories, boxes, permissions... all components and properties for the module
Parameters
DoliDB $db Database handler
Set up Module properties.
numero : Id for module (must be unique). You should use a free id and check http://wiki.dolibarr.org/index.php/List_of_modules_id for available ranges.
rights_class : Key text used to identify module (for permissions, menus, etc...)
family : used to group modules in module setup page. Family can be 'crm','financial','hr','projects','products','ecm','technic','other'
name : module name using this class name without space used if translation string 'ModuleXXXName' not found (where XXX is value of $this->numero)
description : used if translation string 'ModuleXXXDesc' not found
descriptionlong : Can be a full HTML content, not used yet
editor name and editor url
version : module version as x.x.x
const_name : module constant to save module status enabled/disabled
picto : image file used for the module
Call private functions to initialize complex properties
Definition at line 69 of file modVignoble.class.php.
References $conf, $db, $langs, getBoxes(), getConfigPages(), getConstant(), getDataDirectories(), getDependencies(), getDictionaries(), getExports(), getImports(), getLanguageFiles(), getMenuEntries(), getParts(), getPermissions(), and getTabs().
Member Function Documentation
modVignoble::getBoxes () private
Get module boxes array.
Module boxes or widgets could be displayed on Dolibarr Dashboard
file contains the box class file name
note displays in widget set-up page
enablebydefaulton to have widget on home page
Definition at line 700 of file modVignoble.class.php.
Referenced by __construct().
modVignoble::getConfigPages () private
Get the configuration pages url stored in config_page_url array.
The entry is written as "<page file name>@<module name>" and should be stored in module/admin directory. Only one entry is needed, others are optional and create extra links in module list.
Definition at line 178 of file modVignoble.class.php.
Referenced by __construct().
modVignoble::getConstant () private
Get list of custom constants from const array.
Constant are added when module is enabled
Definition at line 628 of file modVignoble.class.php.
Referenced by __construct().
modVignoble::getDataDirectories () private
Get custom data directories in document folder.
Directories are created when module is enabled. Example: this->dirs = array("/module/temp");
Definition at line 168 of file modVignoble.class.php.
Referenced by __construct().
modVignoble::getDependencies () private
Get dependencies attributes and arrays for the module.
Set hidden with a condition to hide module
Set depends array with list of modules class name as string that must be enabled if this module is enabled Example : $this->depends('modAnotherModule', 'modYetAnotherModule')
Todo:
check issue with Dolibarr when module needed is after current module in list
Set requiredby array with list of modules id to disable if this one is disabled
Set conflictwith array with list of modules id this module is in conflict with
Set phpmin as minimum version of PHP required by the module
set need_dolibarr_version as minimum version of Dolibarr required by module
Todo:
check issue when version contains -alpha
Definition at line 188 of file modVignoble.class.php.
Referenced by __construct().
modVignoble::getDictionaries ($conf) private
Get module tables using the Dolibarr dictionary.
List of tables and properties are stored in dictionnaries array.
Define the following dictionnaries
Cultivation Type
Varietal
Rootstock
Definition at line 721 of file modVignoble.class.php.
References $conf.
Referenced by __construct().
modVignoble::getExports () private
Get exports available for the module.
Exports definition are stored in multiple arrays. Each export is located by its main index
Todo:
check example in Skeleton modMyModuleClass.php and see how to implement custom attributes
Define Plot export
Get extrafields
Define export fields
Define export type for fields supported format are Date, Text, Boolean or Numeric
Define export entities for fields (all from Plots)
To add unique key if we ask a field of a child to avoid the DISTINCT to discard them
sql request to extract the data
Definition at line 509 of file modVignoble.class.php.
References $db, $extrafields, and $extrafieldslabels.
Referenced by __construct().
modVignoble::getImports () private
Get imports available for the module.
Imports definition are stored in multiple arrays. Each import is located by its main index.
Define Plots Import
Get Plot extrafields
Define imported entities for each field (needed to fix Dolibarr issue)
Define List of tables to insert into (insert done in same order)
Define List of fields updated by import
define rules to populate user and key fields
use aliastable.field =>'user->id' to get current user
use aliastable.field => 'lastrowid-'.tableparent to get parent row id
Populate validation rules using regex
Populate values for the example file
Definition at line 845 of file modVignoble.class.php.
References $db, $extrafields, $extrafieldslabels, $resql, $sql, and $value.
Referenced by __construct().
modVignoble::getLanguageFiles () private
Get module langage files url stored in langfiles array.
Language files are stored in /langs/<language code>="">/<module>.lang
Definition at line 234 of file modVignoble.class.php.
Referenced by __construct().
modVignoble::getMenuEntries () private
Get module menu entries stored in a menu array.
Each entry is a key, value array in the menu array.
Todo:
add permission rules for menu entries
Define Vignoble top menu entry
Define plot left menu
Define plot left menu entry New plot
Define plot left menu entry Plot List
Define cultivation left menu
Define cultivation left menu entry new cultivation task
Define plot left menu entry cultivation tasks List
Definition at line 362 of file modVignoble.class.php.
Referenced by __construct().
modVignoble::getParts () private
Get module parts array.
Part are custom components overriding Dolibarr defaults
Set triggers to 1 if module has its own trigger directory
Set login to 1 if module has its own login method directory
Set substitutions to 1 if module has its own substitution function file
Set barcode to 1 if module has its own barcode directory Check if obsolete
Set models this to 1 if module has its own PDF or ODT models directory add models in /core/modules/[originmodulename]/doc/[modelfile]
Set css array to relative path of css if module has its own css file loaded after Dolibarr CCS
Set js array to relative path of js files if module must load js on all pages
Set hooks array by adding all hooks context managed by module
Definition at line 647 of file modVignoble.class.php.
Referenced by __construct().
modVignoble::getPermissions () private
Get module permissions stored in rights array.
Each row is a permission defined by an id, a label, a boolean and two constant strings.
Set read, create/modify, delete, export and import permissions for Plot
Definition at line 311 of file modVignoble.class.php.
Referenced by __construct().
modVignoble::getTabs () private
Get module tabs stored in tabs array.
Each line in the array add a module tab to an existing object. The following object type are supported
'categories_x' to add a tab in category view (replace 'x' by type of category (0=product, 1=supplier, 2=customer, 3=member)
'contact' to add a tab in contact view
'contract' to add a tab in contract view
'group' to add a tab in group view
'intervention' to add a tab in intervention view
'invoice' to add a tab in customer invoice view
'invoice_supplier' to add a tab in supplier invoice view
'member' to add a tab in fundation member view
'opensurveypoll' to add a tab in opensurvey poll view
'order' to add a tab in customer order view
'order_supplier' to add a tab in supplier order view
'payment' to add a tab in payment view
'payment_supplier' to add a tab in supplier payment view
'product' to add a tab in product view
'propal' to add a tab in propal view
'project' to add a tab in project view
'resource' to add a tab in resource view
'stock' to add a tab in stock view
'thirdparty' to add a tab in third party view
'user' to add a tab in user view
add plot tab to resource module
remove project tabs for cultivation project
Definition at line 267 of file modVignoble.class.php.
Referenced by __construct().
modVignoble::init ($options = '')
Function called when module is enabled.
The init function add constants, boxes, permissions and menus (defined in constructor) into Dolibarr database. It also creates data directories
Parameters
string $options Options when enabling module ('', 'noboxes')
Returns
int 1 if OK, 0 if KO
Definition at line 798 of file modVignoble.class.php.
References $result, $sql, and loadTables().
modVignoble::loadTables () private
Create tables, keys and data required by module Files llx_table1.sql, llx_table1.key.sql llx_data.sql with create table, create keys and create data commands must be stored in directory /vignoble/sql/ This function is called by this->init.
Returns
int <=0 if KO, >0 if OK
Definition at line 835 of file modVignoble.class.php.
Referenced by init().
modVignoble::remove ($options = '')
Function called when module is disabled.
Remove from database constants, boxes and permissions from Dolibarr database. Data directories are not deleted
Parameters
string $options Options when enabling module ('', 'noboxes')
Returns
int 1 if OK, 0 if KO
Definition at line 818 of file modVignoble.class.php.
References $sql.
The documentation for this class was generated from the following file:
core/modules/modVignoble.class.php