Vignoble: cultivationtaskplot.php File Reference
cultivationtaskplot.php File Reference
Cultivation management
plots target for a cultivation project task
Functions
addPlotTask ($id)
Add plot(s) to the task using the add plots form data.
updatePlotTask ()
update plot line of task using plot line form data
deletePlotTask ()
delete plot line of task using plot line form data
displayAddPlotForm ($id)
Display the add plot form to associate one or more plots to the task.
displayPlotTaskLines ($action, $formother, $plottask)
Display the plot task lines in a table with the capability to edit or delete a line.
getsort ()
Get fields and order used for the plot task table sort.
getfilter ($id)
Get all data needed to filter the SQL requests on plot task and produce the results.
buildSearchParameters ($filter)
Build the parameters string to be added to URL to keep the filter conditions.
Variables
$cultivationprojectid = setIsCultivationProject()
$id = GETPOST('id', 'int')
$ref = GETPOST('ref', 'alpha')
$action = GETPOST('action', 'alpha')
$confirm = GETPOST('confirm', 'alpha')
$cancel = GETPOST('cancel', 'alpha')
Detailed Description
plots target for a cultivation project task
Definition in file cultivationtaskplot.php.
Function Documentation
addPlotTask ($id)
Add plot(s) to the task using the add plots form data.
Parameters
int $id the Id of the current task.
Returns
string $action empty
Definition at line 157 of file cultivationtaskplot.php.
References $action, $conf, $db, $error, $id, $langs, $object, $plot, $result, and $user.
buildSearchParameters ($filter)
Build the parameters string to be added to URL to keep the filter conditions.
(used for list sort)
Parameters
Array $filter the filter conditions including $id
Returns
string to be added to URL
Definition at line 469 of file cultivationtaskplot.php.
References $filter.
deletePlotTask ()
delete plot line of task using plot line form data
Returns
string $action empty
Definition at line 240 of file cultivationtaskplot.php.
References $action, $conf, $db, $error, $langs, $result, and $user.
displayAddPlotForm ($id)
Display the add plot form to associate one or more plots to the task.
The form includes a multi selection list for plots with a note and a progress declaration.
Parameters
int $id the current task id
Definition at line 268 of file cultivationtaskplot.php.
References $_SERVER, $_SESSION, $conf, $db, $formother, $id, $langs, $object, $plot, $user, $value, and print.
displayPlotTaskLines ($action, $formother, $plottask)
Display the plot task lines in a table with the capability to edit or delete a line.
Each line display plot ref and label, note and coverage.
Parameters
action when value is 'editline' the corresponding line is in edit mode
formother needed to use the select a percentage control
$plottask the result of the SQL query on plot task
Definition at line 334 of file cultivationtaskplot.php.
References $_SERVER, $action, $conf, $db, $formother, $langs, $plot, $user, and print.
getfilter ($id)
Get all data needed to filter the SQL requests on plot task and produce the results.
Parameters
int $id the current task id
Returns
Array[] containing the following keys : id (of the task), reference (of the plot), note, coverage, plot (array of sql filter conditions for plot task),
Definition at line 426 of file cultivationtaskplot.php.
References $filter, and $id.
getsort ()
Get fields and order used for the plot task table sort.
Use Ref Ascending by default.
Returns
Array[] with keys : field, order.
Definition at line 397 of file cultivationtaskplot.php.
References $sortfield, and $sortorder.
updatePlotTask ()
update plot line of task using plot line form data
Returns
string $action empty
Definition at line 213 of file cultivationtaskplot.php.
References $action, $conf, $db, $error, $langs, $result, and $user.
Variable Documentation
$action = GETPOST('action', 'alpha')
Definition at line 34 of file cultivationtaskplot.php.
Referenced by addPlotTask(), deletePlotTask(), displayPlotTaskLines(), and updatePlotTask().
$cancel = GETPOST('cancel', 'alpha')
Definition at line 36 of file cultivationtaskplot.php.
$confirm = GETPOST('confirm', 'alpha')
Definition at line 35 of file cultivationtaskplot.php.
$cultivationprojectid = setIsCultivationProject()
Definition at line 28 of file cultivationtaskplot.php.
$id = GETPOST('id', 'int')
Definition at line 31 of file cultivationtaskplot.php.
Referenced by addPlotTask(), displayAddPlotForm(), and getfilter().
$ref = GETPOST('ref', 'alpha')
Definition at line 32 of file cultivationtaskplot.php.